const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'../frontend');
const context=vm.createContext({console,Date,Set,Map,JSON});context.window=context;
for(const f of ['config/contracts.js','domain/cycle.js','services/project-file.js','services/exchange.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});
const {domain:D,projectFile:J,exchange:X}=context.Production;
const plain=x=>JSON.parse(JSON.stringify(x));
function stage(seq,parentUid=null,status='work'){return {uid:'s'+seq,seq,sort:seq,parentUid,title:'Этап '+seq,executor:'Исполнитель',addressees:'Предприятие',start:'2026-09-01',deadline:'2026-09-15',status}}
function fixture(stages=[]){return {project:{orderNo:'123',name:'Проект',initiator:'Инициатор',executor:'Исполнитель',addressees:'Предприятие',start:'2026-09-01',deadline:'2026-09-30'},stages,nextSeq:1+stages.reduce((n,s)=>Math.max(n,s.seq),0),collapsed:{}}}
const shapes=[[],[stage(1)],[stage(1),stage(2),stage(3)],[stage(1),stage(2,'s1'),stage(3,'s2'),stage(4,'s3'),stage(5,'s4')],[stage(1),stage(2),stage(3,'s1'),stage(4,'s3'),stage(5,'s2')]];
for(const [i,stages] of shapes.entries())test('tree/TXT round-trip shape '+i,()=>{const s=fixture(stages),pair=X.exportPair(s),tree=X.previewPair('\ufeff'+pair.out,'\ufeff'+pair.in);assert.equal(tree.stages.length,stages.length);for(const row of tree.stages){const source=stages.find(x=>D.stageId(s,x)===row.id);assert.equal(row.parentId,source.parentUid?D.stageId(s,stages.find(x=>x.uid===source.parentUid)):'123')}assert.equal(tree.manualStatusAvailable,false)});
test('TXT bytes, columns, dates, empty link',()=>{const pair=X.exportPair(fixture([stage(1)]));for(const [key,count] of [['out',9],['in',8]]){assert.equal(Buffer.from('\ufeff'+pair[key]).subarray(0,3).toString('hex'),'efbbbf');assert.ok(!/(^|[^\r])\n/.test(pair[key]));const lines=pair[key].slice(0,-2).split('\r\n');for(const line of lines)assert.equal(line.split('\t').length,count);assert.equal(lines[1].split('\t').at(-1),'')}assert.ok(pair.out.includes('01.09.26\t'));assert.ok(pair.in.includes('01.09.2026\t'));assert.ok(!pair.in.includes('PRODUCTION_TREE'))});
test('cycle, missing parent and duplicate IDs rejected',()=>{for(const list of [[stage(1,'s1')],[stage(1,'s2'),stage(2,'s1')],[stage(1,'missing')],[stage(1),stage(1)]])assert.ok(D.validate(fixture(list)).errors.length)});
test('invalid JSON never returned as replacement',()=>{const s=fixture([stage(1)]);s.stages[0].status='unknown';assert.throws(()=>J.parse(JSON.stringify({format:'production-cycle-builder-v8',...s})));assert.throws(()=>J.parse('{}'));});
test('invalid counters rejected and missing counter derived',()=>{const s=fixture([stage(5)]);s.nextSeq=5;assert.throws(()=>J.stringify(s));delete s.nextSeq;assert.equal(J.parse(JSON.stringify({format:'production-cycle-builder-v8',...s})).nextSeq,6)});
test('JSON roundtrip preserves manual status, seq and parent',()=>{const s=fixture([stage(1,null,'done'),stage(3,'s1','hold')]);assert.deepEqual(plain(J.parse(J.stringify(s))),s)});
test('moving stage preserves export ID and blocked descendants include subtree',()=>{const s=fixture([stage(1),stage(2,'s1'),stage(3,'s2')]);const id=D.stageId(s,s.stages[1]);assert.ok(D.descendants(s,'s1').has('s3'));s.stages[1].parentUid=null;assert.equal(D.stageId(s,s.stages[1]),id);assert.equal(D.validate(s).errors.length,0)});
test('subtree deletion preserves other roots',()=>{const s=fixture([stage(1),stage(2,'s1'),stage(3)]),ids=D.descendants(s,'s1');ids.add('s1');s.stages=s.stages.filter(x=>!ids.has(x.uid));assert.deepEqual(s.stages.map(x=>x.uid),['s3'])});
test('calendar dates and TSV control characters validated',()=>{for(const v of ['2026-02-30','2026-13-01','oops'])assert.equal(D.validDate(v),false);assert.ok(D.validDate('2024-02-29'));const s=fixture([stage(1)]);s.stages[0].title='x\ty';assert.throws(()=>X.exportPair(s));s.stages[0].title='x';s.stages[0].start='2026-10-01';assert.ok(D.validate(s).errors.length)});
test('calendar days independent of DST',()=>{assert.equal(D.daysLeft('2026-03-30','2026-03-28'),2)});
test('KPI and risks use one read-only model',()=>{const s=fixture([stage(1,null,'done'),stage(2,null,'hold'),stage(3),stage(4,null,'new')]);s.stages[1].deadline='2026-09-02';s.stages[2].deadline='2026-09-03';s.stages[3].deadline='2026-09-15';const before=JSON.stringify(s),r=D.report(s,'2026-09-08');assert.equal(r.total,4);assert.equal(r.donePercent,25);assert.equal(r.counts.overdue,1);assert.equal(r.counts.hold,1);assert.equal(r.overdueHeld,1);assert.equal(r.dueSoon,1);assert.equal(JSON.stringify(s),before);assert.equal(D.report(fixture(),'2026-09-08').donePercent,0)});
test('dates 0 to 7 days inclusive, done excluded',()=>{const s=fixture([stage(1),stage(2),stage(3),stage(4,null,'done')]);s.stages[0].deadline='2026-09-08';s.stages[1].deadline='2026-09-15';s.stages[2].deadline='2026-09-16';assert.equal(D.report(s,'2026-09-08').dueSoon,2)});
test('malformed paired tree rejected',()=>{const pair=X.exportPair(fixture([stage(1)])),out='\ufeff'+pair.out,input='\ufeff'+pair.in;for(const invalid of [out.replace('\r\n1\t','\r\n2\t'),out.replace('\r\n1\t','\r\n0\t'),out.replace('\r\n1\t','\r\n-1\t')])assert.throws(()=>X.previewPair(invalid,input));assert.throws(()=>X.previewPair(out,input.replace('123-001','456-001')));assert.throws(()=>X.previewPair(pair.out,input))});
test('iterative tree handles deep imported structure',()=>{const s=fixture(Array.from({length:2500},(_,i)=>stage(i+1,i?'s'+i:null)));assert.equal(D.preorder(s).at(-1).depth,2499)});
test('print layout retains A4 landscape and table continuation',()=>{const css=fs.readFileSync(path.join(root,'styles/app.css'),'utf8');assert.match(css,/size:A4 landscape/);assert.match(css,/display:table-header-group/);assert.match(css,/break-inside:avoid/);const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html,/id="pdfReportBtn"/);assert.ok(!/https?:\/\//.test(html))});
